### ISSUE TITLE
Event types

### ISSUE THREAD

**Issue by rosscado** [rosscado/raceready#38]
Rename Event `type` field to `event_type`.
This will allow us to reserve the fieldname `type` for resource/object/document type, which might be useful in cloudant persistence later.

E.g.
```yaml
   id : uuid
   title: My Race
   type: event
   event_type: road race
```
