### ISSUE TITLE
Stage course info

### ISSUE THREAD

**Issue by rosscado** [rosscado/raceready#41]
Represent a [stage's `course`](
https://github.com/rosscado/raceready/wiki/Data-Model#stage) as laps (1 or more) of a [`circuit`](
https://github.com/rosscado/raceready/wiki/Data-Model#circuit) (mapped route or segment).

[Example](https://github.com/rosscado/raceready/blob/worked_examples/tests/fvt/test_laragh_classic.tavern.yaml):
```yaml
races:
          - title: Friends First Laragh Classic
            eligible_categories:
              - A1
              - A2
            stage_type: road race
            handicapped: false
            start_time: "2018-09-01 11:00"
            course:
              laps: 1
              circuit_id: {circuit_id}
```
