### ISSUE TITLE
Circuit entity

### ISSUE THREAD

**Issue by rosscado** [rosscado/raceready#43]
Create a circuit entity at endpoint `/api/circuits/`

https://github.com/rosscado/raceready/wiki/Data-Model#circuit

*Schema*
```yaml
id:
URL: web address of the mapped route or segment, e.g. Strava route/segment
elevation_gain_m: elevation gained (in metres) over one lap of the circuit, e.g. 250
distance_km: length (in kilometres) of one lap of the circuit, e.g. 12
flatness_index: computed, indicates how close to flat is the circuit, e.g. 0.15
```

*Example*
```yaml
  - name: Create the circuit
    request:
      url: "{api.server}/api/circuits/"
      json:
        url: https://www.mapmyride.com/routes/view/2189856949
        distance_km: 86.95
        elevation_gain_m: 1315
      method: POST
      headers:
        content-type: application/json
    response:
      status_code: 201
```

For now all fields except `flatness_index` will be populated by client POST/PUT requests exclusively. In later iterations `distance_km` and `elevation_gain_m` and other fields may be parsed from the route information at `url`.
