### ISSUE TITLE
add a `social_media` model for clubs and events

### ISSUE THREAD

**Issue by rosscado** [rosscado/raceready#49]
Example:
```yaml
        title: Laragh Classic
        date: "2018-09-01"
        event_type: road race
          club:
            title: St. Tiernans Cycling Club
            url: http://www.sttiernanscc.com/
            social_media:
              handle: "@StTiernansCC"
        social_media:
          hashtag: "#LaraghClassic"
```
