### ISSUE TITLE
add a registration entity to events

### ISSUE THREAD

**Issue by rosscado** [rosscado/raceready#50]
Add a `registration` field to `Event` entities representing the ways in which racers can sign up for the event.

Example:
```yaml
registration:
          methods:
            - type: online
              url: https://register.primoevents.com/ps/event/FriendsFirstLaraghClassic2018
              state: closed
            - type: ontheday
              state: limited
```
