### ISSUE TITLE
capture additional event URLs, e.g. primary, CI, etc.

### ISSUE THREAD

**Issue by rosscado** [rosscado/raceready#51]
`Event` entities currently have a single field `URL` representing the primary URL of the event.

Add more fields for other URLs promoting the event, if they exist e.g.
 * Cycling Ireland's official event URL
 * Facebook event

These could be represented as discrete fields if the number of supported URLs is low, or a nested list of fields if the number of URLs is high or unbounded.
_Discrete_
```yaml 
url_primary: http://www.sttiernanscc.com/
url_ci: https://cyclingireland.azolve.com/Workbench.mvc/public/eventDetails?EventId=1077384
```
_Nested_
```yaml 
urls:
 primary: http://www.sttiernanscc.com/
 cycling_ireland: https://cyclingireland.azolve.com/Workbench.mvc/public/eventDetails?EventId=1077384
```
_List_
```yaml
urls:
 - type: primary
   url: http://www.sttiernanscc.com/
 - type: Cycling Ireland 
   url: https://cyclingireland.azolve.com/Workbench.mvc/public/eventDetails?EventId=1077384
```
