### ISSUE TITLE
Category eligibility for races/stages

### ISSUE THREAD

**Issue by rosscado** [rosscado/raceready#52]
This will allow athletes to filter events to match their own category/categories.

The category in `eligible_categories` list will match an id in `/api/categories/{id}`. E.g. `/api/categories/A1`.

Example:
```yaml
   stages:
          - title: Friends First Laragh Classic
            eligible_categories:
              - A1
              - A2
```
