### ISSUE TITLE
Club Entities

### ISSUE THREAD

**Issue by rosscado** [rosscado/raceready#62]
Separate the club entity from the POST event request, since we won't be recreating clubs on every event.
This will then require a means of looking up the club and linking the event to it.
E.g.
```yaml
club:
   id: Lucan Cycling Road Club
...
event:
   organised_by:
     club_id: Lucan Cycling Road Club
```
Or
`club_id = GET /api/clubs/?title=Lucan Cycling Road Club`
```yaml
event:
   organised_by:
     club_id: {club_id}
```

_Originally posted by @rosscado in https://github.com/rosscado/raceready/issues/57#issuecomment-419850195_
